// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: services/payments-service/proto/accounts.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_services_payments_service_proto_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_payments_service_proto_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_services_payments_service_proto_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BankId        string                 `protobuf:"bytes,3,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_services_payments_service_proto_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_payments_service_proto_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_services_payments_service_proto_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *AccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountResponse) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *AccountResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type UpdateBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	IsCredit      bool                   `protobuf:"varint,3,opt,name=is_credit,json=isCredit,proto3" json:"is_credit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceRequest) Reset() {
	*x = UpdateBalanceRequest{}
	mi := &file_services_payments_service_proto_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceRequest) ProtoMessage() {}

func (x *UpdateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_payments_service_proto_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_services_payments_service_proto_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateBalanceRequest) GetIsCredit() bool {
	if x != nil {
		return x.IsCredit
	}
	return false
}

var File_services_payments_service_proto_accounts_proto protoreflect.FileDescriptor

const file_services_payments_service_proto_accounts_proto_rawDesc = "" +
	"\n" +
	".services/payments-service/proto/accounts.proto\x12\baccounts\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"w\n" +
	"\x0fAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\abank_id\x18\x03 \x01(\tR\x06bankId\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\"j\n" +
	"\x14UpdateBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1b\n" +
	"\tis_credit\x18\x03 \x01(\bR\bisCredit2\xa2\x01\n" +
	"\x0eAccountService\x12D\n" +
	"\n" +
	"GetAccount\x12\x1b.accounts.GetAccountRequest\x1a\x19.accounts.AccountResponse\x12J\n" +
	"\rUpdateBalance\x12\x1e.accounts.UpdateBalanceRequest\x1a\x19.accounts.AccountResponseB\tZ\a./protob\x06proto3"

var (
	file_services_payments_service_proto_accounts_proto_rawDescOnce sync.Once
	file_services_payments_service_proto_accounts_proto_rawDescData []byte
)

func file_services_payments_service_proto_accounts_proto_rawDescGZIP() []byte {
	file_services_payments_service_proto_accounts_proto_rawDescOnce.Do(func() {
		file_services_payments_service_proto_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_payments_service_proto_accounts_proto_rawDesc), len(file_services_payments_service_proto_accounts_proto_rawDesc)))
	})
	return file_services_payments_service_proto_accounts_proto_rawDescData
}

var file_services_payments_service_proto_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_payments_service_proto_accounts_proto_goTypes = []any{
	(*GetAccountRequest)(nil),    // 0: accounts.GetAccountRequest
	(*AccountResponse)(nil),      // 1: accounts.AccountResponse
	(*UpdateBalanceRequest)(nil), // 2: accounts.UpdateBalanceRequest
}
var file_services_payments_service_proto_accounts_proto_depIdxs = []int32{
	0, // 0: accounts.AccountService.GetAccount:input_type -> accounts.GetAccountRequest
	2, // 1: accounts.AccountService.UpdateBalance:input_type -> accounts.UpdateBalanceRequest
	1, // 2: accounts.AccountService.GetAccount:output_type -> accounts.AccountResponse
	1, // 3: accounts.AccountService.UpdateBalance:output_type -> accounts.AccountResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_payments_service_proto_accounts_proto_init() }
func file_services_payments_service_proto_accounts_proto_init() {
	if File_services_payments_service_proto_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_payments_service_proto_accounts_proto_rawDesc), len(file_services_payments_service_proto_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_payments_service_proto_accounts_proto_goTypes,
		DependencyIndexes: file_services_payments_service_proto_accounts_proto_depIdxs,
		MessageInfos:      file_services_payments_service_proto_accounts_proto_msgTypes,
	}.Build()
	File_services_payments_service_proto_accounts_proto = out.File
	file_services_payments_service_proto_accounts_proto_goTypes = nil
	file_services_payments_service_proto_accounts_proto_depIdxs = nil
}
