// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: services/payments-service/proto/payments.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayerId       string                 `protobuf:"bytes,1,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	PayeeId       string                 `protobuf:"bytes,2,opt,name=payee_id,json=payeeId,proto3" json:"payee_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_services_payments_service_proto_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_payments_service_proto_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_services_payments_service_proto_payments_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetPayerId() string {
	if x != nil {
		return x.PayerId
	}
	return ""
}

func (x *PaymentRequest) GetPayeeId() string {
	if x != nil {
		return x.PayeeId
	}
	return ""
}

func (x *PaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_services_payments_service_proto_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_payments_service_proto_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_services_payments_service_proto_payments_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_services_payments_service_proto_payments_proto protoreflect.FileDescriptor

const file_services_payments_service_proto_payments_proto_rawDesc = "" +
	"\n" +
	".services/payments-service/proto/payments.proto\x12\bpayments\"z\n" +
	"\x0ePaymentRequest\x12\x19\n" +
	"\bpayer_id\x18\x01 \x01(\tR\apayerId\x12\x19\n" +
	"\bpayee_id\x18\x02 \x01(\tR\apayeeId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"b\n" +
	"\x0fPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2V\n" +
	"\x0ePaymentService\x12D\n" +
	"\rCreatePayment\x12\x18.payments.PaymentRequest\x1a\x19.payments.PaymentResponseB\tZ\a./protob\x06proto3"

var (
	file_services_payments_service_proto_payments_proto_rawDescOnce sync.Once
	file_services_payments_service_proto_payments_proto_rawDescData []byte
)

func file_services_payments_service_proto_payments_proto_rawDescGZIP() []byte {
	file_services_payments_service_proto_payments_proto_rawDescOnce.Do(func() {
		file_services_payments_service_proto_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_payments_service_proto_payments_proto_rawDesc), len(file_services_payments_service_proto_payments_proto_rawDesc)))
	})
	return file_services_payments_service_proto_payments_proto_rawDescData
}

var file_services_payments_service_proto_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_payments_service_proto_payments_proto_goTypes = []any{
	(*PaymentRequest)(nil),  // 0: payments.PaymentRequest
	(*PaymentResponse)(nil), // 1: payments.PaymentResponse
}
var file_services_payments_service_proto_payments_proto_depIdxs = []int32{
	0, // 0: payments.PaymentService.CreatePayment:input_type -> payments.PaymentRequest
	1, // 1: payments.PaymentService.CreatePayment:output_type -> payments.PaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_payments_service_proto_payments_proto_init() }
func file_services_payments_service_proto_payments_proto_init() {
	if File_services_payments_service_proto_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_payments_service_proto_payments_proto_rawDesc), len(file_services_payments_service_proto_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_payments_service_proto_payments_proto_goTypes,
		DependencyIndexes: file_services_payments_service_proto_payments_proto_depIdxs,
		MessageInfos:      file_services_payments_service_proto_payments_proto_msgTypes,
	}.Build()
	File_services_payments_service_proto_payments_proto = out.File
	file_services_payments_service_proto_payments_proto_goTypes = nil
	file_services_payments_service_proto_payments_proto_depIdxs = nil
}
