// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: services/settlement-service/proto/settlement.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettlementStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId   string                 `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementStatusRequest) Reset() {
	*x = SettlementStatusRequest{}
	mi := &file_services_settlement_service_proto_settlement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementStatusRequest) ProtoMessage() {}

func (x *SettlementStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_settlement_service_proto_settlement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementStatusRequest.ProtoReflect.Descriptor instead.
func (*SettlementStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_settlement_service_proto_settlement_proto_rawDescGZIP(), []int{0}
}

func (x *SettlementStatusRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type SettlementStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId   string                 `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementStatusResponse) Reset() {
	*x = SettlementStatusResponse{}
	mi := &file_services_settlement_service_proto_settlement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementStatusResponse) ProtoMessage() {}

func (x *SettlementStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_settlement_service_proto_settlement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementStatusResponse.ProtoReflect.Descriptor instead.
func (*SettlementStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_settlement_service_proto_settlement_proto_rawDescGZIP(), []int{1}
}

func (x *SettlementStatusResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *SettlementStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_services_settlement_service_proto_settlement_proto protoreflect.FileDescriptor

const file_services_settlement_service_proto_settlement_proto_rawDesc = "" +
	"\n" +
	"2services/settlement-service/proto/settlement.proto\x12\n" +
	"settlement\"<\n" +
	"\x17SettlementStatusRequest\x12!\n" +
	"\freference_id\x18\x01 \x01(\tR\vreferenceId\"U\n" +
	"\x18SettlementStatusResponse\x12!\n" +
	"\freference_id\x18\x01 \x01(\tR\vreferenceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2u\n" +
	"\x11SettlementService\x12`\n" +
	"\x13GetSettlementStatus\x12#.settlement.SettlementStatusRequest\x1a$.settlement.SettlementStatusResponseB\tZ\a./protob\x06proto3"

var (
	file_services_settlement_service_proto_settlement_proto_rawDescOnce sync.Once
	file_services_settlement_service_proto_settlement_proto_rawDescData []byte
)

func file_services_settlement_service_proto_settlement_proto_rawDescGZIP() []byte {
	file_services_settlement_service_proto_settlement_proto_rawDescOnce.Do(func() {
		file_services_settlement_service_proto_settlement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_settlement_service_proto_settlement_proto_rawDesc), len(file_services_settlement_service_proto_settlement_proto_rawDesc)))
	})
	return file_services_settlement_service_proto_settlement_proto_rawDescData
}

var file_services_settlement_service_proto_settlement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_settlement_service_proto_settlement_proto_goTypes = []any{
	(*SettlementStatusRequest)(nil),  // 0: settlement.SettlementStatusRequest
	(*SettlementStatusResponse)(nil), // 1: settlement.SettlementStatusResponse
}
var file_services_settlement_service_proto_settlement_proto_depIdxs = []int32{
	0, // 0: settlement.SettlementService.GetSettlementStatus:input_type -> settlement.SettlementStatusRequest
	1, // 1: settlement.SettlementService.GetSettlementStatus:output_type -> settlement.SettlementStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_settlement_service_proto_settlement_proto_init() }
func file_services_settlement_service_proto_settlement_proto_init() {
	if File_services_settlement_service_proto_settlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_settlement_service_proto_settlement_proto_rawDesc), len(file_services_settlement_service_proto_settlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_settlement_service_proto_settlement_proto_goTypes,
		DependencyIndexes: file_services_settlement_service_proto_settlement_proto_depIdxs,
		MessageInfos:      file_services_settlement_service_proto_settlement_proto_msgTypes,
	}.Build()
	File_services_settlement_service_proto_settlement_proto = out.File
	file_services_settlement_service_proto_settlement_proto_goTypes = nil
	file_services_settlement_service_proto_settlement_proto_depIdxs = nil
}
